### ISSUE TITLE
Provide more UI Components  and Utils from the UI-Kit

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-docs-kit#1233]
For building a PoC / MVP self learning portal in the docs style it would help significantly to have much more components exposed from the UI-Kit package, which are currently inside the `gatsby-theme-docs` package. 

- [X] Markdown fragment renderer (could require allowing Javascript in the Typescript settings, the unified plugin systematics are nontrivial to type).   Addressed in #1236 (migrated)
- [ ] Maybe more of the other utils (scroll to top, sentry reporting,...)
- [X] Cards  (requires the above). Addressed in #1236  (card elements provided, but not the full "boxed" card)
- [ ] The layout internals as far as they are independent of gatsbyJS data structures.  Layouts themselves are gatsby specific.  (migrating "layout elements" is in progress:  https://github.com/commercetools/commercetools-docs-kit/tree/nk-move-layout-elements-to-uikit ) 
- [ ] The pagination buttons (just the styled components, not the full component that holds the gatsby specific  logic)  
- [ ] Icons (e.g. the burger icon) - Addressed in #1236   (icons migrated,  burger in progress in https://github.com/commercetools/commercetools-docs-kit/tree/nk-move-layout-elements-to-uikit ) 
- [ ]  SideBySideContainer  
 
Can (and likely should) be done in multiple steps and PRs

**Comment by nkuehn** [comment]
FYI @FFawzy

**Comment by FFawzy** [comment]
Summary: it turned out to cause more troubles than anticipated, so we will close this for now.
