### ISSUE TITLE
Content Alternative Paths

### ISSUE THREAD

**Issue by FFawzy** [commercetools/commercetools-docs-kit#2036]
Use case: 

the ability to offer alternative paths in content depending on the user's choice.
for example: in developer modules a user might decide to continue reading the module in JS language, or in Java. 
some pieces of the content might then be different accordingly.
also when the user picks an option it should be reflected in all other alternative paths within the same module (for example if the user picks JS, the rest of the module should be in JS too)

this feature is not restricted to developer languages only too, a content author might write a module in a way that a user can explore it in Merchant Center, or in JS 

take this [Google example](https://cloud.google.com/run/docs/configuring/shared-vpc-direct-vpc#deploy-service), you can explore content in `Console or gcloud, or YAML or Terraform`

the feature must be able to remember the user selection during the same module (or in all modules?)

```[tasklist]
### Tasks
- [ ] https://github.com/commercetools/commercetools-docs-kit/issues/2060
- [ ] https://github.com/commercetools/commercetools-docs-kit/issues/2054
- [ ] https://github.com/commercetools/commercetools-docs-kit/issues/2059
- [ ] https://github.com/commercetools/commercetools-docs-kit/issues/2055
```

```[tasklist]
### Dependencies
- [x] The solution for this use case will likely be the same as we need here: https://github.com/commercetools/commercetools-docs-kit/issues/1786
```

**Comment by zbalek** [comment]
Hi @FFawzy, I have now prepared a [solution exploration page](https://commercetools.atlassian.net/wiki/x/YYBKP) for this piece which includes different alternatives for the component. I have also checked with the Shield team designer who suggested to check with the shield team devs / Nicola to see the impact of using the app kit components. I have left it as an action item.

**Comment by FFawzy** [comment]
I think this can be closed @zbalek its implemented and live
